# This file configures your dbt project.
# For a full list of options, see the dbt documentation:
# https://docs.getdbt.com/reference/dbt_project-yml

name: 'edgar_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'edgar_analytics'

# These configurations apply to all models in the project.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"