# This file configures your dbt project.

name: 'edgar_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'edgar_analytics'

# These configurations apply to all models in your project.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL and logs
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"