# For more information on configuring profiles, please see:
# https://docs.getdbt.com/docs/core/connect-data-platform/profiles.yml

# This profile is configured to be used by the main.py orchestrator.
# The `dbt` command in main.py sets the DBT_PROFILES_DIR to the project root.
edgar_analytics:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'C:/Users/user/Documents/edgar_data/db/edgar_analytics.duckdb'
      # Add any extensions you use, e.g.:
      # extensions:
      #   - "httpfs"