version: 2

sources:
  - name: edgar_raw # This name is arbitrary, but should be descriptive
    # This tells dbt to look in your 'dev' target database (from profiles.yml)
    database: '{{ target.database }}' 
    schema: main # DuckDB's default schema
    tables:
      - name: companies
      - name: filings
      - name: xbrl_facts
      - name: tickers
      # Add other raw tables here as you need them (e.g., yf_income_statement)